### ISSUE TITLE
Array-iterate does not iterate

### ISSUE THREAD

**Issue by jaumemir** [chromecide/node-red-contrib-primitives#1]
It only outputs the first element of the array, and the node indicates the number of remaining items, but no more items are output.
Seems a loop is missing.

**Comment by chromecide** [comment]
Hi, sorry it's taken so long to reply, I didn't get a notification of this issue being raised.  The iterate node does not handle the looping on it's own. The node that handles processing each item must then be connected back to the iterate input, to trigger the next item to be processed.

There is an example of how to use the iterate node here:

http://flows.nodered.org/flow/b8baf6ff25bea4a16124
