### ISSUE TITLE
How to use bool-toggle

### ISSUE THREAD

**Issue by marksev1** [chromecide/node-red-contrib-primitives#2]
Can you maybe tell me how I can use bool-toggle...I'd like to toggle it, so that it changes output like true/false/true/false,etc..But currently it just gives true all the time.

**Comment by chromecide** [comment]
The output of the node is whether the specified property on the context object was toggled, not the actual value itself.  For example your context(or global context) object has a _bProcessed_ property.  You would specify that as the property in the bool-toggle node and it would be the _bProcessed_ property that is changed.

**Comment by marksev1** [comment]
Can you post maybe an example flow please?

**Comment by chromecide** [comment]
Try this, should give you a basic idea of how it works.  Remember the Debug is outputting the value of msg.isProcessed, not the value coming out of bool-toggle.

[{
    "id": "5d773e27.a629b",
    "type": "function",
    "z": "af3997a6.50c668",
    "name": "Create Context with Bool Prop",
    "func": "msg.isProcessed = false\nreturn msg;",
    "outputs": 1,
    "noerr": 0,
    "x": 330,
    "y": 481,
    "wires": [
        ["2d651e87.ce6092", "48434441.9c92dc"]
    ]
}, {
    "id": "4a05d804.d5c0a8",
    "type": "inject",
    "z": "af3997a6.50c668",
    "name": "",
    "topic": "",
    "payload": "",
    "payloadType": "none",
    "repeat": "",
    "crontab": "",
    "once": false,
    "x": 101,
    "y": 482,
    "wires": [
        ["5d773e27.a629b"]
    ]
}, {
    "id": "2d651e87.ce6092",
    "type": "debug",
    "z": "af3997a6.50c668",
    "name": "",
    "active": true,
    "console": "false",
    "complete": "isProcessed",
    "x": 721,
    "y": 480,
    "wires": []
}, {
    "id": "48434441.9c92dc",
    "type": "bool-toggle",
    "z": "af3997a6.50c668",
    "name": "Toggle isProcessed",
    "source_object": "msg",
    "source_property": "isProcessed",
    "x": 561,
    "y": 581,
    "wires": [
        ["2d651e87.ce6092"]
    ]
}]
